using webapi_test.Entity;

namespace webapi_test.Models;

// indicate Book implement IEntity, Book.cs is generated by entity framework
// modify Book.cs will be overwrote by EF
public partial class Book : IEntity<int>
{
}